---
title: 'Alex/Trevor Bird Abundance Data: K=4'
author: "Kushal K Dey"
date: "April 18, 2016"
output: html_document
---
## Overview
  
We apply deeptpx model on Alex/Trevor bird abundance data. We perform the deeptpx model for $4$ topics at the bottom layer and $2$ topics at the top layer (so total 2 layers of topics).

## Data Preparation

```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
library(plotrix)
data=read.csv("Himalayan_grid_matrix.csv",header=TRUE);

counts=as.matrix(data[,-1]);

rownames(counts)=data[,1];

new_data1 <- data.frame(read.csv('MohanGrids.csv'));
new_data2 <- data.frame(read.csv('MohanGrids2.csv'));

bird_species <- union(as.vector(colnames(counts)), union(as.vector(new_data1[,1]), as.vector(new_data2[,1])));

new_data <- matrix(0,dim(counts)[1]+3,length(bird_species));
new_data[1,match(new_data1[,1],bird_species)]=new_data1[,2];
new_data[2,match(new_data1[,1],bird_species)]=new_data1[,3];
new_data[3,match(new_data2[,1],bird_species)]=new_data2[,2];
new_data[4:(dim(counts)[1]+3),match(colnames(counts),bird_species)]=counts;

new_counts <- as.matrix(new_data);

rownames(new_counts) <- c(c("U1","U2","MA"),rownames(counts));
colnames(new_counts) <- bird_species;

new_counts <- new_counts[,colnames(new_counts[,which(colSums(new_counts) > 0)])]

cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

metadata <- read.csv("gridsmeta.csv",header=T)
metadata <-metadata[c(9,8,1,10,6,2,3,36,7,11,5,33,4,30,14,32,31,12,13,37,15,34,19,38,18,35,17,23,16,24,28,21,26,20,27,25,22,29),]
row.names(metadata) <- metadata$GRID
east_west_dir = metadata$WorE
forest_patch_label <- row.names(metadata)

elevation_metadata=metadata$Elevation;

ordered_counts <- new_counts

```

## deeptpx application

```{r}
topic_clus <- maptpx::topics(ordered_counts, K=4, tol=0.00000000001, bf=T);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

### topic model K=4

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
K <- 4
par(mfrow=c(1,1))
{barplot(t(docweights[forest_patch_label,]),col=cbbPalette[1:K],axisnames=F,space=0,border=NA,
        main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)
title(main=paste("Taxonomic Assemblage Motifs, K =",K))
combo_patch_dir = paste0(forest_patch_label,"_",east_west_dir);
combo_patch_dir_ordered = combo_patch_dir[order(east_west_dir)];
match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],38);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);
labs=c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5,21.5,22.5,23.5,24.5,25.5,26.5,27.5,28.5,29.5,30.5,31.5,32.5,33.5,34.5,35.5,36.5,37.5)
axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
ablineclip(v=match_labs[0:length(match_labs)],y1=0,y2=1);}
```

### metatopic for K=3

```{r echo=TRUE, eval=TRUE}
libsize_birds <- rowSums(ordered_counts);

omega_1 <- topic_clus$omega
theta_1 <- topic_clus$theta

lambda_1 <- sweep(omega_1, 1, libsize_birds, "*");

z_level_1 <- array(0,c(dim(lambda_1)[1], dim(theta_1)[1], dim(lambda_1)[2]));
for(k in 1:dim(theta_1)[2]){
  z_level_1[,,k] <- floor(lambda_1[,k]%*%t(theta_1[,k]))
}

z_level_1_counts <- apply(z_level_1, c(1,3), sum);
rownames(z_level_1_counts) <- rownames(ordered_counts)
```

```{r echo=TRUE, eval=TRUE}
topic_clus <- maptpx::topics(z_level_1_counts, K=3, tol=0.0001);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
par(mfrow=c(1,1))
K<-3
{barplot(t(docweights[forest_patch_label,]),col=cbbPalette[1:K],axisnames=F,space=0,border=NA,
        main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)
title(main=paste("Taxonomic Assemblage Motifs, K =",K))
combo_patch_dir = paste0(forest_patch_label,"_",east_west_dir);
combo_patch_dir_ordered = combo_patch_dir[order(east_west_dir)];
match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],38);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);
labs=c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5,21.5,22.5,23.5,24.5,25.5,26.5,27.5,28.5,29.5,30.5,31.5,32.5,33.5,34.5,35.5,36.5,37.5)
axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
ablineclip(v=match_labs[0:length(match_labs)],y1=0,y2=1);}
```


### metatopic for K=2

```{r echo=TRUE, eval=TRUE}
libsize_birds <- rowSums(z_level_1_counts);

omega_2 <- topic_clus$omega
theta_2 <- topic_clus$theta

lambda_2 <- sweep(omega_2, 1, libsize_birds, "*");

z_level_2 <- array(0,c(dim(lambda_2)[1], dim(theta_2)[1], dim(lambda_2)[2]));
for(k in 1:dim(theta_2)[2]){
  z_level_2[,,k] <- floor(lambda_2[,k]%*%t(theta_2[,k]))
}

z_level_2_counts <- apply(z_level_2, c(1,3), sum);
rownames(z_level_2_counts) <- rownames(ordered_counts)
```

```{r echo=TRUE, eval=TRUE}
topic_clus <- maptpx::topics(z_level_2_counts, K=2, tol=0.0001);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
forest_patch_labels <- forest_patch_label[-26]
east_west_dirs <- east_west_dir[-26]
K <- 2
par(mfrow=c(1,1))
{barplot(t(docweights[forest_patch_labels,]),col=cbbPalette[1:K],axisnames=F,space=0,border=NA,
        main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)
title(main=paste("Taxonomic Assemblage Motifs, K =",K))
combo_patch_dir = paste0(forest_patch_labels,"_",east_west_dirs);
combo_patch_dir_ordered = combo_patch_dir[order(east_west_dirs)];
match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],37);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);
labs=c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5,21.5,22.5,23.5,24.5,25.5,26.5,27.5,28.5,29.5,30.5,31.5,32.5,33.5,34.5,35.5,36.5)
axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
ablineclip(v=match_labs[0:length(match_labs)],y1=0,y2=1);}

```

## Standard topic model with bodymass ordered

```{r}

bodymass_data <- read.csv('massKushal.csv');

bodymass_val <- bodymass_data[,2];
bodymass_birds <- bodymass_data[,1];

bodymass_matched <- bodymass_data[match(colnames(new_counts),bodymass_birds),2];
summary(bodymass_matched)

ordered_counts <- new_counts[,order(bodymass_matched, decreasing = FALSE)];

topic_clus <- maptpx::topics(ordered_counts, K=4, tol=0.00000000001, bf=T);
docweights <- topic_clus$omega
theta <- topic_clus$theta
```

### topic model K=4, bodymass ordered

```{r echo=TRUE, eval=TRUE, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
K <- 4
par(mfrow=c(1,1))
{barplot(t(docweights[forest_patch_label,]),col=cbbPalette[1:K],axisnames=F,space=0,border=NA,
        main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)
title(main=paste("Taxonomic Assemblage Motifs, K =",K))
combo_patch_dir = paste0(forest_patch_label,"_",east_west_dir);
combo_patch_dir_ordered = combo_patch_dir[order(east_west_dir)];
match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],38);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);
labs=c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5,21.5,22.5,23.5,24.5,25.5,26.5,27.5,28.5,29.5,30.5,31.5,32.5,33.5,34.5,35.5,36.5,37.5)
axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
ablineclip(v=match_labs[0:length(match_labs)],y1=0,y2=1);}
```

