---
title: 'ordtpx on Alex data: adaptive approach'
author: "Kushal K Dey"
date: "May 7, 2016"
output: html_document
---

```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
library(devtools)
#install_github('kkdey/ordtpx')
library(ordtpx)
library(maptpx)
library(smashr)
library(slam)
```

```{r echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}
library(HimalayanBirdsAbundance)
data("HimalayanBirdsAbundance")
new_counts <- t(exprs(HimalayanBirdsAbundance));
metadata <- pData(HimalayanBirdsAbundance);

elevation_metadata=metadata$Elevation;
east_west_dir = metadata$WorE;

bodymass_data <- read.csv('../external_data/massKushal.csv');

bodymass_val <- bodymass_data[,2];
bodymass_birds <- bodymass_data[,1];

bodymass_matched <- bodymass_data[match(colnames(new_counts),bodymass_birds),2];
summary(bodymass_matched)

ordered_counts <- new_counts[,order(bodymass_matched, decreasing = FALSE)];


```

## ordtpx (K=2) - smash

```{r}
source("../../../ordtpx/R/ord_count.R")
source("../../../ordtpx/R/ord_mra.R")
source("../../../ordtpx/R/ord_tpx.R")
source("../../../ordtpx/R/tpx.R")
source("../../../ordtpx/R/ord_topics.R")
source("../../../ordtpx/R/count.R")
source("../../../ordtpx/R/binshrink.R")
```


```{r echo=TRUE, eval=TRUE}
library(ordtpx)
levels <- ceiling(log(dim(ordered_counts)[2])/log(2))+1;

scale <- 2
del_beta <- scale*(10^{1:(levels-1)})
Topic_clus <- ord_topics(ordered_counts, K=2, ztree_options=1, tol=0.1,
                         init_method = "taddy", adapt.method="smash",
                         burn_trials = 1, tmax_start = 2)
Topic_clus$loglik
```

### Structure Plot - elevation

```{r echo=TRUE, eval=TRUE}
K <- 2
par(mfrow=c(1,1))
barplot(t(Topic_clus$omega[order(elevation_metadata),]),col=2:(K+1),axisnames=F,space=0,border=NA,main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4, xlab="elevation")
title(main=paste("Structure Plot topic proportions,k=",K))
combo_patch_dir = paste0(round(elevation_metadata));
combo_patch_dir_ordered = combo_patch_dir[order(elevation_metadata)];

match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
abline(v=match_labs[2:length(match_labs)]);

```

### Cluster plots 

```{r echo=TRUE, eval=TRUE}
par(mfrow=c(1,2))
plot(Topic_clus$theta[,1], type="l")
plot(Topic_clus$theta[,2], type="l")
```

## ordtpx (K=3)- smash

```{r echo=TRUE, eval=TRUE}

Topic_clus <- ord_topics(ordered_counts, K=3, ztree_options=1, tol=0.1,
                         init_method = "taddy", adapt.method="smash",
                         burn_trials = 1, tmax_start = 2)
Topic_clus$loglik
#print(scale)
```

### Structure Plot - by East-west and elevation

```{r echo=TRUE, eval=TRUE}
par(mfrow=c(1,1))
docweights <- Topic_clus$omega
east_west_elevation = paste0(metadata$WorE, "_", metadata$Elevation);

index1 <- which(metadata$WorE=="E");
index2 <- which(metadata$WorE=="W");
elevation1 <- metadata$Elevation[index1]; elevation2 <- metadata$Elevation[index2];
index_WE <- c(index1[order(elevation1)], index2[order(elevation2)]);

  K <- 3
    barplot(t(docweights[index_WE,]),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",3),las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

    combo_patch_dir = paste0(east_west_elevation);
    combo_patch_dir_ordered = combo_patch_dir[index_WE];

  match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
  match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
  match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
  labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

  axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
  abline(v=match_labs[2:length(match_labs)]);
```

### Structure plot - by elevation

```{r echo=TRUE, eval=TRUE}
K <- 3
par(mfrow=c(1,1))
barplot(t(Topic_clus$omega[order(elevation_metadata),]),col=2:(K+1),axisnames=F,space=0,border=NA,main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4, xlab="elevation")
title(main=paste("Structure Plot topic proportions,k=",K))
combo_patch_dir = paste0(round(elevation_metadata));
combo_patch_dir_ordered = combo_patch_dir[order(elevation_metadata)];

match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
abline(v=match_labs[2:length(match_labs)]);

```

### Cluster plots

```{r echo=TRUE, eval=TRUE}
par(mfrow=c(1,3))
plot(Topic_clus$theta[1:305,1], type="l")
plot(Topic_clus$theta[1:305,2], type="l")
plot(Topic_clus$theta[1:305,3], type="l")

```



```{r echo=FALSE, eval=FALSE}
library(ordtpx)
levels <- ceiling(log(dim(ordered_counts)[2])/log(2))+1;

scale <- 2
del_beta <- scale*(10^{1:(levels-1)})
Topic_clus <- ord_topics(ordered_counts, K=2, ztree_options=1, tol=0.1,
                         init_method = "taddy", adapt.method="bash",
                         burn_trials = 10, tmax_start = 2)
Topic_clus$loglik
```


```{r echo=FALSE, eval=FALSE}
K <- 2
par(mfrow=c(1,1))
barplot(t(Topic_clus$omega[order(elevation_metadata),]),col=2:(K+1),axisnames=F,space=0,border=NA,main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4, xlab="elevation")
title(main=paste("Structure Plot topic proportions,k=",K))
combo_patch_dir = paste0(round(elevation_metadata));
combo_patch_dir_ordered = combo_patch_dir[order(elevation_metadata)];

match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
abline(v=match_labs[2:length(match_labs)]);

```


```{r echo=FALSE, eval=FALSE}
par(mfrow=c(1,2))
plot(Topic_clus$theta[,1], type="l")
plot(Topic_clus$theta[,2], type="l")
```


```{r echo=FALSE, eval=FALSE}

Topic_clus <- ord_topics(ordered_counts, K=3, ztree_options=1, tol=0.1,
                         init_method = "taddy", adapt.method="bash",
                         burn_trials = 1, tmax_start = 2)
Topic_clus$loglik
#print(scale)
```


```{r echo=FALSE, eval=FALSE}
par(mfrow=c(1,1))
docweights <- Topic_clus$omega
east_west_elevation = paste0(metadata$WorE, "_", metadata$Elevation);

index1 <- which(metadata$WorE=="E");
index2 <- which(metadata$WorE=="W");
elevation1 <- metadata$Elevation[index1]; elevation2 <- metadata$Elevation[index2];
index_WE <- c(index1[order(elevation1)], index2[order(elevation2)]);

  K <- 3
    barplot(t(docweights[index_WE,]),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",3),las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

    combo_patch_dir = paste0(east_west_elevation);
    combo_patch_dir_ordered = combo_patch_dir[index_WE];

  match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
  match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
  match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
  labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

  axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
  abline(v=match_labs[2:length(match_labs)]);
```


```{r echo=FALSE, eval=FALSE}
K <- 3
par(mfrow=c(1,1))
barplot(t(Topic_clus$omega[order(elevation_metadata),]),col=2:(K+1),axisnames=F,space=0,border=NA,main="",las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4, xlab="elevation")
title(main=paste("Structure Plot topic proportions,k=",K))
combo_patch_dir = paste0(round(elevation_metadata));
combo_patch_dir_ordered = combo_patch_dir[order(elevation_metadata)];

match_labs=match(unique(combo_patch_dir_ordered),combo_patch_dir_ordered);
match_labs_suffix=c(match_labs[2:length(unique(combo_patch_dir_ordered))],35);
match_labs_prefix=match_labs[1:(length(unique(combo_patch_dir_ordered)))];
labs=match_labs_prefix + 0.5*(match_labs_suffix - match_labs_prefix);

axis(1,at=labs,unique(combo_patch_dir_ordered),las=2);
abline(v=match_labs[2:length(match_labs)]);

```


```{r echo=FALSE, eval=FALSE}
par(mfrow=c(1,3))
plot(Topic_clus$theta[1:305,1], type="l")
plot(Topic_clus$theta[1:305,2], type="l")
plot(Topic_clus$theta[1:305,3], type="l")

```
